name: Integrate

on:
  push:
    branches: [ main ]
  pull_request:
  workflow_dispatch:

jobs:
  code-quality:
    runs-on: depot-ubuntu-24.04-arm-16
    steps:
      - name: Checkout code
        uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4.2.2

      - name: Setup Biome
        uses: biomejs/setup-biome@f382a98e582959e6aaac8e5f8b17b31749018780 # v2.5.0
      - name: Run Biome
        run: biome ci

      - name: Setup Node.js
        uses: actions/setup-node@1d0ff469b7ec7b3cb9d8673fde0c81c44821de2a # v4.2.0
        with:
          node-version: lts/*

      - name: Install dependencies
        run: npm install -g pnpm && pnpm install

      - name: Run tsc
        run: pnpm tsc
